In [1]:
import numpy as np

In [2]:
a = np.genfromtxt('data/src/sample_nan.csv', delimiter=',')
print(a)

[[11. 12. nan 14.]
 [21. nan nan 24.]
 [31. 32. 33. 34.]]


In [3]:
print(np.isnan(a))

[[False False  True False]
 [False  True  True False]
 [False False False False]]


In [4]:
print(~np.isnan(a))

[[ True  True False  True]
 [ True False False  True]
 [ True  True  True  True]]


In [5]:
print(a[~np.isnan(a)])

[11. 12. 14. 21. 24. 31. 32. 33. 34.]


In [6]:
print(np.isnan(a).any(axis=1))

[ True  True False]


In [7]:
print(~np.isnan(a).any(axis=1))

[False False  True]


In [8]:
print(a[~np.isnan(a).any(axis=1), :])

[[31. 32. 33. 34.]]


In [9]:
print(a[~np.isnan(a).any(axis=1)])

[[31. 32. 33. 34.]]


In [10]:
print(~np.isnan(a).any(axis=0))

[ True False False  True]


In [11]:
print(a[:, ~np.isnan(a).any(axis=0)])

[[11. 14.]
 [21. 24.]
 [31. 34.]]


In [12]:
a = np.genfromtxt('data/src/sample_nan.csv', delimiter=',')
a[2, 2] = np.nan
print(a)

[[11. 12. nan 14.]
 [21. nan nan 24.]
 [31. 32. nan 34.]]


In [13]:
print(a[:, ~np.isnan(a).any(axis=0)])

[[11. 14.]
 [21. 24.]
 [31. 34.]]


In [14]:
print(a[:, ~np.isnan(a).all(axis=0)])

[[11. 12. 14.]
 [21. nan 24.]
 [31. 32. 34.]]
