In [1]:
from PIL import Image
import numpy as np

In [2]:
im = np.array(Image.open('data/src/lena.jpg'))

In [3]:
print(im.shape)

(225, 400, 3)


In [4]:
print(im[100, 150])

[111  81 109]


In [5]:
print(type(im[100, 150]))

<class 'numpy.ndarray'>


In [6]:
R, G, B = im[100, 150]

In [7]:
print(R)

111


In [8]:
print(G)

81


In [9]:
print(B)

109


In [10]:
print(im[100, 150, 0])

111


In [11]:
print(im[100, 150, 1])

81


In [12]:
print(im[100, 150, 2])

109


In [13]:
im[100, 150] = (0, 50, 100)

In [14]:
print(im[100, 150])

[  0  50 100]


In [15]:
im[100, 150, 0] = 150

In [16]:
print(im[100, 150])

[150  50 100]
