In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2, 3)
print(a)

[[0 1 2]
 [3 4 5]]


In [3]:
b = np.zeros_like(a)
print(b)

[[0 0 0]
 [0 0 0]]


In [4]:
print(a)

[[0 1 2]
 [3 4 5]]


In [5]:
a[:, :] = 0
print(a)

[[0 0 0]
 [0 0 0]]


In [6]:
a[:] = 1
print(a)

[[1 1 1]
 [1 1 1]]


In [7]:
a[:] = 0.1
print(a)

[[0 0 0]
 [0 0 0]]


In [8]:
a = a.astype(np.float)
a[:] = 0.1
print(a)

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
