In [1]:
import numpy as np

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
a_0 = a[:6]
print(a_0)

[0 1 2 3 4 5]


In [4]:
a_1 = a_0.reshape(2, 3)
print(a_1)

[[0 1 2]
 [3 4 5]]


In [5]:
print(a_0.base)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(a_1.base)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
a_copy = a.copy()
print(a_copy)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
print(a_copy.base)

None


In [9]:
print(a.base)

None


In [10]:
print(a_0.base is None)

False


In [11]:
print(a_copy.base is None)

True


In [12]:
print(a.base is None)

True


In [13]:
print(a_0.base is a)

True


In [14]:
print(a_0.base is a_1.base)

True
